apiVersion: apps/v1
kind: Deployment
metadata:
  name: rheo-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rheor-app
  template:
    metadata:
      labels:
        app: rheo-app
    spec:
      containers:
        - name: rheo-app
          image: public.ecr.aws/p5u3f5g6/rheo-flask-app-pub:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
