apiVersion: apps/v1
kind: Deployment
metadata:
  name: rheo-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rheor-app
  template:
    metadata:
      labels:
        app: rheo-app
    spec:
      containers:
        - name: rheo-app
          image: 211125528700.dkr.ecr.us-west-2.amazonaws.com/rheo-flask-app:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
