apiVersion: v1
kind: Service
metadata:
  name: rheo-app-service
  labels:
    app: rheo-app 
spec:
  selector:
    app: rheo-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
